# Change these first
owner: ayo0wen # Your GitHub organization or username, where this repository lives
repo: ohwegayuptime # The name of this repository

sites:
  - name: Main Site
    url: http://www.ohwen.gay
  - name: Cookie Clicker Host
    url: http://cookie.ohwen.gay
  - name: 2nd Host
    url: https://2nd.ohwen.gay

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.ohwen.gay
  # baseUrl: /your-repo-name
  theme: ocean
  logoUrl: https://cdn.discordapp.com/attachments/960953474986696716/961349085896531968/0.png
  name: ohwen.gay Status
  introTitle: "Welcome to the uptime of https://ohwen.gay"
  introMessage: ohwen.gay uptime
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration

i18n:
 footer: Found an issue with any of my services? Contact me on Discord **ohwen#0106**
 activeIncidents: ⚠️ Active Incidents
 allSystemsOperational: All Systems Operational
 liveStatus: 🔴 Live Status Monitor
 pastIncidents: ✅ Past Incidents
